### ISSUE TITLE
Watchnixtoons

### ISSUE THREAD

**Issue by doko-desuka** [alexnander/hello-world#3]
Hi @alexnander
I was thinking of rewriting plugin.video.watchnixtoons, I think there's some places where it can be optimised a little, plus take out some other stuff that's unused, and also to write it to work with Kodi 18 (Leia).
When it's finished, could you give it a look (to give your opinion)?

**Comment by bjgood** [comment]
I'd like to give it try too, doko. Be a test monkey, of sorts. :).

Have a good one
Bob

**Comment by doko-desuka** [comment]
It's in here:
https://github.com/doko-desuka/plugin.video.watchnixtoons2/raw/master/plugin.video.watchnixtoons2-0.1.0.zip

Still under tests though. Don't expect much!

**Comment by doko-desuka** [comment]
Alright, so this is a preliminary version of a different add-on, Toonmania2:
https://github.com/doko-desuka/plugin.video.toonmania2

@alexnander if you have some idea of a better site for scraping or some way to improve it, do come by and let me know.
